spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/event_management
    username: postgres
    password: root
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          github:
            client-id: fdffdf #client id--------------
            client-secret: fdfdfdf #secret--------------
            scope: read:user, user:email

            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            client-name: GitHub
app:
  frontend:
    url: http://localhost:5173



